import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { Toaster } from "~/components/ui/sonner";
import { Inter } from "next/font/google";
import { TopNav } from "~/app/_components/topnav";
import { ourFileRouter } from "./api/uploadthing/core";
import "@uploadthing/react/styles.css";
import { CSPostHogProvider } from "~/app/_analytics/providers";

const inter = Inter({
  subsets: ["latin"],
  style: "normal",
  weight: "900",
  variable: "--font-sans",
});

export const metadata = {
  title: "ewGALLERY",
  description: "Generated by me using create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <CSPostHogProvider>
        <html lang="en">
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <body className={`${inter.variable} dark gap-4 font-sans`}>
            <div className="grid h-screen grid-rows-[auto,1fr]">
              <TopNav />
              <main className="overflow-y-scroll">{children}</main>
            </div>
            {modal}
            <div id="modal-root" />
            <Toaster />
          </body>
        </html>
      </CSPostHogProvider>
    </ClerkProvider>
  );
}
