import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";

import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";

import { TopNav } from "~/app/_components/topnav";
import { ourFileRouter } from "./api/uploadthing/core";

import "@uploadthing/react/styles.css";

const inter = Inter({
  subsets: ["latin"],
  style: "normal",
  weight: "900",
  variable: "--font-sans",
});

export const metadata = {
  title: "ewGALLERY",
  description: "Generated by me using create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <body className={`${inter.variable} flex flex-col gap-4 font-sans`}>
          <TopNav />
          {children}
          {modal}
          <div id="modal-root" />
        </body>
      </html>
    </ClerkProvider>
  );
}
