import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";

const inter = Inter({
  subsets: ["latin"],
  style: "normal",
  weight: "900",
  variable: "--font-sans",
});

export const metadata = {
  title: "ewGALLERY",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between border-b p-4">
      <div className={`${inter.variable} font-sans`}> G.A.L.L.E.R.Y.</div>
      <ul>
        <li>Sign-in</li>
      </ul>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} flex flex-col gap-4 font-sans`}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
